version = 1
SPDX-PackageName = "weave-openclaw"
SPDX-PackageSupplier = "CoreWeave, Inc."
SPDX-PackageDownloadLocation = "https://github.com/wandb/weave-openclaw"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 CoreWeave, Inc."
SPDX-License-Identifier = "MIT"
